FROM alpine:3.8
MAINTAINER Mario Cho "m.cho@lablup.com"

# Install Git extras and some Python packages
RUN apk add --no-cache --virtual .buildeps \
	gcc g++ make cmake libxml2-dev libxslt-dev libc-dev python3-dev openssl && \
    apk add --no-cache git bash jq libxml2 util-linux openssh-client gawk curl py3-pip vim && \
    mkdir -p /tmp/git-flow && cd /tmp/git-flow && \
    wget --no-check-certificate -q https://raw.githubusercontent.com/petervanderdoes/gitflow-avh/develop/contrib/gitflow-installer.sh && \
    sh gitflow-installer.sh install stable && \
    cd /tmp && rm -rf /tmp/git-flow && \
    mkdir -p /tmp/libgit-build && cd /tmp/libgit-build && \
    wget https://github.com/libgit2/libgit2/archive/v0.28.2.tar.gz && \
    tar xzf v0.28.2.tar.gz && \
    cd libgit2-0.28.2/ && \
    cmake . && \
    make -j8 && \
    make install && \
    cd /tmp && rm -rf /tmp/libgit-build

# Backend.AI specifics
ENV LD_LIBRARY_PATH=/opt/backend.ai/lib
RUN apk add --no-cache libffi libzmq
COPY policy.yml /etc/backend.ai/jail/policy.yml
LABEL ai.backend.kernelspec="1" \
      ai.backend.features="batch query uid-match user-input" \
      ai.backend.base-distro="alpine3.8" \
      ai.backend.resource.min.cpu="1" \
      ai.backend.resource.min.mem="256m" \
      ai.backend.runtime-type="c" \
      ai.backend.runtime-path="/usr/bin/gcc" \
      ai.backend.service-ports=""

# vim: ft=dockerfile
