package policy

var AllowedSyscalls []string

func init() {
    AllowedSyscalls = []string {
        "open",
        "read",
        "write",
        "close",
        "openat",
        "stat",
        "lstat",
        "fstat",
        "statfs",
        "access",
        "mmap",
        "mprotect",
        "munmap",
        "brk",
        "lseek",
        "getdents",
        "readlink",
        "dup",
        "creat",
        "rt_sigaction",
        "rt_sigprocmask",
        "sigaltstack",
        "arch_prctl",
        "prctl",
        "getrlimit",
        "set_tid_address",
        "clear_tid_address",
        "set_robust_list",
        "get_robust_list",
        "futex",
        "sched_getaffinity",
        "sched_setaffinity",
        "gettid",
        "getuid",
        "geteuid",
        "getgid",
        "getegid",
        "getcwd",
        "socket",
        "socketpair",
        "connect",
        "ioctl",
        "fcntl",
        "select",
        "poll",
        "epoll_create",
        "epoll_create1",
        "epoll_wait",
        "epoll_ctl",
        "rename",
        "unlink",
        "exit_group",
        // potentially replaced with VDSO
        "getpid",
        "getpgid",
        "getsid",
        "clock_gettime",
        "clock_getres",
        "clock_nanosleep",
        // required to launch user program
        "execve",
    }
}


