FROM lablup/common-base:20.06-py36-cuda10.1

# Install TensorFlow, Keras, PyTorch and MXNet
ENV TENSORFLOW_VERSION=2.2.0
ENV PYTORCH_VERSION=1.5.0
ENV TORCHVISION_VERSION=0.6.0
ENV TORCHAUDIO_VERSION=0.5.0
ENV TORCHTEXT_VERSION=0.6.0
ENV TENSORBOARDX_VERSION=1.9
ENV MXNET_VERSION=1.5.1
ARG CUDA=10.1
ARG LIBNVINFER=6.0.1-1
ARG LIBNVINFER_MAJOR_VERSION=6
ENV CUDNN_VERSION=7.6.4.38-1+cuda10.1
ENV NCCL_VERSION=2.5.7-1+cuda10.1
ENV DEBIAN_FRONTEND=noninteractive
ENV mecab_dicdir /usr/local/lib/mecab/dic/mecab-ko-dic
ENV MPLBACKEND=Svg
ENV PYTHONUNBUFFERED=1 \
    LD_LIBRARY_PATH="/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/local/nvidia/lib64:/usr/include/x86_64-linux-gnu" \
    PATH="/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin/mecab" \
    LANG=C.UTF-8

# Set default shell to /bin/bash
SHELL ["/bin/bash", "-cu"]

RUN python3 -m pip install pip --no-cache-dir \
	    tensorflow-transform==0.22.0 \
	    tensorflow_model_analysis==0.21.6 \
	    ngraph-tensorflow-bridge==0.18.0 \
	    adanet==0.8.0

RUN python3 -m pip install pip --no-cache-dir \
	    pandas==1.0.4 \
    	    tensorflow-gpu==${TENSORFLOW_VERSION} \
       	    tensorboard==2.2.2 \
	    tensorflow-metadata==0.22.1 \
	    tensorflow-datasets==3.1.0 \
	    tensorflow_probability==0.10.0  \
	    tensorflow-addons==0.10.0 \
	    neural-structured-learning==1.1.0 \
	    tensorflow-model-optimization==0.3.0 \
	    tensorflow-hub==0.8.0 \
	    tensorflow_text==2.2.0 \
	    tensorflow-graphics-gpu==1.0.0 \
	    tensorflow-gan==2.0.0 \
	    tensorflow-data-validation==0.22.0 \
	    fairness-indicators==0.1.2 \
	    tensorboard-plugin-fairness-indicators==0.0.5 \
	    fairness==0.1.8 \
	    tfx==0.21.4 \
	    tfx-bsl==0.22.0 \
	    tf-agents==0.5.0  \
	    tensorflow-lattice-gpu==0.9.8 \ 
	    tensorflow-lattice==2.0.4 \
	    tensorflow_ranking==0.3.1 \
	    tensorflow-compression==1.3 \
	    tensor2tensor==1.15.6 \
	    mesh-tensorflow==0.1.13 \
	    tensorflow-io==0.13.0 \
	    jupyter-tensorboard==0.2.0 \
    	    tensorwatch==0.9.1 \
	    jupyterlab-nvdashboard==0.3.1 

RUN python3 -m pip install pip --no-cache-dir \
        pandas==1.0.4 \
    	https://download.pytorch.org/whl/cu101/torch-${PYTORCH_VERSION}%2Bcu101-cp36-cp36m-linux_x86_64.whl \
        https://download.pytorch.org/whl/cu101/torchvision-${TORCHVISION_VERSION}%2Bcu101-cp36-cp36m-linux_x86_64.whl \
        https://download.pytorch.org/whl/torchaudio-${TORCHAUDIO_VERSION}-cp36-cp36m-linux_x86_64.whl \
        torchtext==${TORCHTEXT_VERSION} && \
    python3 -m pip install --no-cache-dir tensorboardX==${TENSORBOARDX_VERSION}	    

RUN python3 -m pip install --no-cache-dir mxnet-cu101==${MXNET_VERSION}

# Install Horovod, temporarily using CUDA stubs
RUN ldconfig /usr/local/cuda/targets/x86_64-linux/lib/stubs && \
    HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_GPU_BROADCAST=NCCL \
    HOROVOD_WITH_TENSORFLOW=1 HOROVOD_WITH_PYTORCH=1 HOROVOD_WITH_MXNET=1 \
    pip install --no-cache-dir horovod==0.19.4 && \
    ldconfig

RUN python3 -m pip install --no-cache-dir \
    	    mpi4py==3.0.3 \
	    nni==1.6 \
	    scikit-nni==0.2.1

# Install ipython kernelspec
Run python3 -m ipykernel install --display-name "Lablup FF 20.06 on Python 3.6 (CUDA 10.1)" && \
    cat /usr/local/share/jupyter/kernels/python3/kernel.json

# Backend.AI specifics
LABEL ai.backend.kernelspec="1" \
      ai.backend.envs.corecount="OPENBLAS_NUM_THREADS,OMP_NUM_THREADS,NPROC" \
      ai.backend.features="batch query uid-match user-input" \
      ai.backend.base-distro="ubuntu16.04" \
      ai.backend.resource.min.cpu="1" \
      ai.backend.resource.min.mem="1g" \
      ai.backend.resource.min.cuda.device=0 \
      ai.backend.resource.min.cuda.shares=0 \
      ai.backend.runtime-type="python" \
      ai.backend.runtime-path="/usr/bin/python3" \
      ai.backend.service-ports="ipython:pty:3000,tensorboard:http:6006,jupyter:http:8080,jupyterlab:http:8090,mne:http:5000"

WORKDIR /home/work
# vim: ft=dockerfile
