FROM ubuntu:20.04

RUN apt-get update && \
    apt-get install -y \
        ncurses-term && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/
RUN ln -sf /usr/share/terminfo/x/xterm-color /usr/share/terminfo/x/xterm-256color
ENV PYTHONUNBUFFERED=1 \
    PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    LANG=C.UTF-8
COPY filebrowser_amd64 /usr/bin/filebrowser
RUN mkdir /etc/filebrowser
COPY filebrowser.db /etc/filebrowser/filebrowser.db
COPY config.json /etc/filebrowser/config.json
COPY ./filebrowser_static /etc/filebrowser/resources
#COPY bootstrap.sh /opt/container/bootstrap.sh

# Backend.AI specifics
COPY ./service-defs /etc/backend.ai/service-defs
LABEL ai.backend.kernelspec="1" \
      ai.backend.envs.corecount="OPENBLAS_NUM_THREADS,OMP_NUM_THREADS,NPROC" \
      ai.backend.features="batch query uid-match user-input" \
      ai.backend.resource.min.cpu="1" \
      ai.backend.resource.min.mem="256m" \
      ai.backend.base-distro="ubuntu20.04" \
      ai.backend.runtime-type="app" \
      ai.backend.runtime-path="/usr/bin/filebrowser" \
      ai.backend.service-ports="filebrowser:http:8080"
COPY policy.yml /etc/backend.ai/jail/policy.yml

# vim: ft=dockerfile
