FROM ubuntu:20.04
ARG TARGETPLATFORM
RUN apt-get update && \
    apt-get install -y \
        ncurses-term && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/
RUN ln -sf /usr/share/terminfo/x/xterm-color /usr/share/terminfo/x/xterm-256color
ENV PYTHONUNBUFFERED=1 \
    PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    LANG=C.UTF-8
RUN mkdir /etc/filebrowser
COPY filebrowser.db /etc/filebrowser/filebrowser.db
COPY config.json /etc/filebrowser/config.json
COPY ./filebrowser_static /etc/filebrowser/resources
#COPY bootstrap.sh /opt/container/bootstrap.sh
COPY *.bin /tmp/
RUN if [ "$TARGETPLATFORM" = "linux/amd64" ]; then ARCHITECTURE=amd64; elif [ "$TARGETPLATFORM" = "linux/arm/v7" ]; then ARCHITECTURE=arm; elif [ "$TARGETPLATFORM" = "linux/arm64" ]; then ARCHITECTURE=aarch64; else ARCHITECTURE=amd64; fi \
    && cp "/tmp/filebrowser_${ARCHITECTURE}.bin" /usr/bin/filebrowser
#    && COPY filebrowser_amd64 /usr/bin/filebrowser
#COPY filebrowser_"$(echo ${TARGETPLATFORM} | sed -e "s/\//-/g")" /usr/bin/filebrowser
#COPY bin/${$TARGETPLATFORM}/filebrowser /usr/bin/filebrowser

# Backend.AI specifics
COPY ./service-defs /etc/backend.ai/service-defs
LABEL ai.backend.kernelspec="1" \
      ai.backend.envs.corecount="OPENBLAS_NUM_THREADS,OMP_NUM_THREADS,NPROC" \
      ai.backend.features="batch query uid-match user-input private" \
      ai.backend.resource.min.cpu="1" \
      ai.backend.resource.max.cpu="1" \
      ai.backend.resource.min.mem="128m" \
      ai.backend.resource.max.mem="256m" \
      ai.backend.role="SYSTEM" \
      ai.backend.base-distro="ubuntu20.04" \
      ai.backend.runtime-type="app" \
      ai.backend.runtime-path="/usr/bin/filebrowser" \
      ai.backend.service-ports="filebrowser:http:8080"
COPY policy.yml /etc/backend.ai/jail/policy.yml

# vim: ft=dockerfile
