FROM alpine:3.8

# Install minimal C compile environments
RUN apk add --no-cache openssl build-base \
    && apk add --no-cache curl wget zip unzip vim

# RUN apk add --no-cache libseccomp shadow su-exec libstdc++; \
#     mkdir /home/work && chmod 755 /home/work; \
#     mkdir /home/backend.ai && chmod 755 /home/backend.ai
# ADD entrypoint.sh /usr/local/bin/entrypoint.sh
# RUN chmod +x /usr/local/bin/entrypoint.sh
# ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]


# RUN apk add --no-cache ca-certificates \
#         wget \
#         expat gdbm libbz2 libffi openssl ncurses-libs readline sqlite-libs xz-libs zlib

# Install libressl2.7-libssl. edge/main repo should not be added before expat
# installation. That will break pip (incompatible version of libexpat.so.1?).
# RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories && \
#     apk update && apk add --no-cache libressl2.7-libssl

# Backend.AI specifics
# ENV LD_LIBRARY_PATH=/opt/backend.ai/lib
# RUN apk add --no-cache libffi libzmq
COPY policy.yml /etc/backend.ai/jail/policy.yml
LABEL ai.backend.kernelspec="1" \
      ai.backend.features="batch query uid-match user-input" \
      ai.backend.base-distro="alpine3.8" \
      ai.backend.resource.min.cpu="1" \
      ai.backend.resource.min.mem="64m" \
      ai.backend.runtime-type="c" \
      ai.backend.runtime-path="/usr/bin/gcc" \
      ai.backend.service-ports=""

# vim: ft=dockerfile
