FROM lablup/kernel-base-python-minimal:3.6-alpine

# Install minimal C++ compile environments
RUN apk add --no-cache build-base libstdc++

# Install kernel-runner scripts package
RUN pip install --no-cache-dir "backend.ai-kernel-runner[cpp]~=1.1.0"

COPY policy.yml /home/sorna/policy.yml

LABEL io.sorna.features "batch query uid-match"

CMD ["/home/sorna/jail", "-policy", "/home/sorna/policy.yml", \
     "/usr/local/bin/python", "-m", "ai.backend.kernel", "cpp"]

# vim: ft=dockerfile
