FROM ubuntu:20.04
# Install base packages into default Ubuntu 20.04
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && \
    apt-get install -y \
        ca-certificates apt-utils \
        wget curl git-core \
        vim-tiny zip unzip \
        libssl-dev \
        libmpdec2 \
        proj-bin libproj-dev \
        libgeos-dev libgeos++-dev \
        mime-support \
        gcc g++ \
        cmake ncurses-term && \
    ln -sf /usr/share/terminfo/x/xterm-color /usr/share/terminfo/x/xterm-256color && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/

# vim: ft=dockerfile
