FROM lablup/kernel-python3:latest

# Install TensorFlow and Keras
USER root
COPY tensorflow-1.0.0-cp36-cp36m-linux_x86_64.whl /tmp
RUN apk add --no-cache --virtual .sorna-deps libc6-compat \
    && pip install --no-cache-dir /tmp/tensorflow-*.whl \
    && pip install --no-cache-dir keras \
    && rm -f /tmp/*.whl

LABEL io.sorna.timeout="30"
LABEL io.sorna.maxmem="512m"
LABEL io.sorna.maxcores="4"

USER work
