FROM lablup/common-base:py38-cuda11.1

# install kaldi
WORKDIR /opt
RUN apt update ; apt-get install -y sox subversion
RUN git clone https://github.com/hephaex/kaldi.git /opt/kaldi && \
    cd /opt/kaldi/tools && \
    make -j $(nproc) && \
    cd /opt/kaldi/src && \
    ./configure --shared --use-cuda \
	--cudatk-dir=/usr/local/cuda/ \
	--mathlib=ATLAS \
    	--cuda-arch="-gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_80,code=sm_80" && \
    make depend -j $(nproc) && \
    make -j $(nproc) 
RUN cd /opt/kaldi/src  && \
    make ext -j $(nproc) && \
    ldconfig && \
    find /opt/kaldi  -type f \( -name "*.o" -o -name "*.la" -o -name "*.a" \) -\
exec rm {} \; && \
    rm -rf /opt/kaldi/.git

RUN mkdir -p /workspace && \
    chmod -R 777 /workspace
# Install ipython kernelspec
Run python3 -m ipykernel install --display-name "Lablup Kaldi 21.01 on Python 3\
.8 (CUDA 11.1)" && \
    cat /usr/local/share/jupyter/kernels/python3/kernel.json


# Backend.AI specifics
LABEL ai.backend.kernelspec="1" \
      ai.backend.envs.corecount="OPENBLAS_NUM_THREADS,OMP_NUM_THREADS,NPROC" \
      ai.backend.features="batch query uid-match user-input" \
      ai.backend.base-distro="ubuntu16.04" \
      ai.backend.resource.min.cpu="1" \
      ai.backend.resource.min.mem="1g" \
      ai.backend.resource.min.cuda.device=0 \
      ai.backend.resource.min.cuda.shares=0 \
      ai.backend.runtime-type="python" \
      ai.backend.runtime-path="/usr/bin/python3" \
      ai.backend.service-ports="ipython:pty:3000,jupyter:http:8080,jupyterlab:http:8090,vscode:http:8180,tensorboard:http:6006"

WORKDIR /home/work
# vim: ft=dockerfile
