FROM lablup/common-base:py38-cuda11.3

RUN python3 -m pip uninstall -y \
       plaidml-keras==0.7.0 \
       tensorflow==2.3.3 \
       google-api-core \
       tensorflow-estimator==2.3.0 

RUN python3 -m pip install --no-cache-dir --upgrade \
	    -q git+https://github.com/google-research/tensorflow_constrained_optimization
	    
RUN python3 -m pip install --no-cache-dir \
        requests_oauthlib==1.3.1 \
	    neural-structured-learning==1.4.0 \
	    pydot==1.4.2 \
	    proto-plus==1.22.1
RUN python3 -m pip install --no-cache-dir \
	    tensorflow-transform==1.11.0 \
	    tensorflow_model_analysis==0.42.0 \
	    tensorflow-datasets==4.7.0 \
	    tensorflow-datasets-ko==0.2.3 \
	    tensorflow_probability==0.17.0 \ 
	    tensorflow-addons==0.18.0 \
	    tensorflow-model-optimization==0.7.3 \
	    tfx==1.11.0 \
	    tfx-bsl==1.11.0 \ 
	    tf-agents==0.14.0  

RUN python3 -m pip install --no-cache-dir \
	    google_cloud_spanner==1.19.3 \
	    googleapis-common-protos==1.56.4 \
	    google_cloud_videointelligence==1.15.0 \
	    google_cloud_vision==0.42.0 \
	    google_cloud_pubsub==2.13.10 \
	    google_cloud_dlp==3.9.2 \
	    google_cloud_datastore==1.15.5 \
	    google_cloud_bigtable==1.7.2 \
	    google-api-core[grpc,grpcgcp]==1.33.2 \
	    google_api_core==1.33.2

RUN python3 -m pip install --no-cache-dir \
	    mesh-tensorflow==0.1.21 \
        tensorflow-cloud==0.1.16 \
        tensorflow-hub==0.12.0 

RUN python3 -m pip install --no-cache-dir \
	    -i https://pypi-nightly.tensorflow.org/simple tensorflow-data-validation==1.11.0
RUN python3 -m pip install --no-cache-dir \
	    tensorflow-graphics-gpu==1.0.0 \
        tensorflow-io==0.28.0 \
	    tensorflow_ranking==0.5.1 \
	    tensorflow-plot==0.3.2 \
	    tensorflow_text==2.11.0 \
	    tensorflow-gan==2.1.0 
RUN   python3 -m pip install --no-cache-dir \
        tensorflow-gpu==2.11.0 \
	    keras==2.11.0 \
	    Keras-Applications==1.0.8 \
	    Keras-Preprocessing==1.1.2 \
	    tensorboard-plugin-wit \
	    tensorboard numpy scipy
RUN python3 -m pip install --no-cache-dir \
	    transformers \
	    accelerate \
	    xformers \
	    gradio

WORKDIR /tmp
RUN rm -f /usr/local/bin/code-server && \
    rm -fr /usr/local/lib/code-server-* && \
    curl -fL https://github.com/cdr/code-server/releases/download/v4.8.3/code-server-4.8.3-linux-amd64.tar.gz \
    | tar -C /usr/local/lib -xz && \
    mv /usr/local/lib/code-server-4.8.3-linux-amd64 /usr/local/lib/code-server-4.8.3 && \
    ln -s /usr/local/lib/code-server-4.8.3/bin/code-server /usr/local/bin/code-server

# Install Horovod, temporarily using CUDA stubs
RUN ldconfig /usr/local/cuda/targets/x86_64-linux/lib/stubs && \
    HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_GPU_BROADCAST=NCCL HOROVOD_NCCL_LINK=SHARED \
    HOROVOD_WITH_TENSORFLOW=1 HOROVOD_WITHOUT_PYTORCH=1 HOROVOD_WITHOUT_MXNET=1\
    HOROVOD_GPU=CUDA \
    python3 -m pip install --no-cache-dir horovod==0.26.1 && \
    ldconfig

RUN python3 -m pip install --no-cache-dir \
            mpi4py==3.1.4 \
            nni==2.10 \
            mlflow==2.0.1 \
            scikit-nni==0.2.1

# Install ipython kernelspec
Run python3 -m ipykernel install --display-name "TensorFlow 2.11 on Python 3.8 & CUDA 11.3" && \
    cat /usr/local/share/jupyter/kernels/python3/kernel.json

# Copy Backend.Ai multi-node support
COPY ./service-defs /etc/backend.ai/service-defs
COPY ./runner-scripts/bootstrap.sh runner-scripts/setup_multinode.py /opt/container/

# Backend.AI specifics
LABEL ai.backend.kernelspec="1" \
      ai.backend.envs.corecount="OPENBLAS_NUM_THREADS,OMP_NUM_THREADS,NPROC" \
      ai.backend.features="batch query uid-match user-input" \
      ai.backend.base-distro="ubuntu16.04" \
      ai.backend.resource.min.cpu="1" \
      ai.backend.resource.min.mem="1g" \
      ai.backend.resource.min.cuda.device=0 \
      ai.backend.resource.min.cuda.shares=0 \
      ai.backend.runtime-type="python" \
      ai.backend.runtime-path="/usr/bin/python3" \
      ai.backend.service-ports="ipython:pty:3000,jupyter:http:8081,jupyterlab:http:8090,vscode:http:8180,tensorboard:http:6006,mlflow-ui:preopen:5000,nniboard:preopen:8080"
      
WORKDIR /home/work
