FROM cr.backend.ai/internal/common-base:py310-cuda12.4-ubuntu22.04
#FROM lablup/common-base:py310-cuda12.0.0

RUN python3 -m pip uninstall -y \
       plaidml-keras==0.7.0 \
       tensorflow==2.3.3 \
       google-api-core \
       tensorflow-estimator==2.3.0 

RUN python3 -m pip install --no-cache-dir --upgrade \
	    -q git+https://github.com/google-research/tensorflow_constrained_optimization
	    
RUN python3 -m pip install --no-cache-dir \
        requests_oauthlib==1.3.1 \
	    neural-structured-learning==1.4.0 \
	    pydot==1.4.2 \
	    proto-plus==1.22.1
RUN python3 -m pip install --no-cache-dir \
	    tensorflow-transform==1.15.0 \
	    tensorflow_model_analysis==0.46.0 \
	    tensorflow-datasets==4.7.0 \
	    tensorflow-datasets-ko==0.2.3 \
	    tensorflow_probability==0.17.0 \ 
	    tensorflow-addons==0.18.0 \
	    tensorflow-model-optimization==0.7.3 \
	    tfx==1.15.1 \
	    tfx-bsl==1.15.1 \ 
	    tf-agents==0.14.0  

RUN python3 -m pip install --no-cache-dir \
	    google_cloud_spanner==1.19.3 \
	    googleapis-common-protos==1.56.4 \
	    google_cloud_videointelligence==1.15.0 \
	    google_cloud_vision==0.42.0 \
	    google_cloud_pubsub==2.13.10 \
	    google_cloud_dlp==3.9.2 \
	    google_cloud_datastore==1.15.5 \
	    google_cloud_bigtable==1.7.2 \
	    google-api-core[grpc,grpcgcp]==1.33.2 \
	    google_api_core==1.33.2

RUN python3 -m pip install --no-cache-dir \
	    mesh-tensorflow==0.1.21 \
        tensorflow-cloud==0.1.16 \
        tensorflow-hub==0.12.0 

RUN python3 -m pip install --no-cache-dir \
	    -i https://pypi-nightly.tensorflow.org/simple tensorflow-data-validation==1.15.1
RUN python3 -m pip install --no-cache-dir \
        tensorflow-io==0.28.0 \
	    tensorflow_ranking==0.5.1 \
	    tensorflow-plot==0.3.2 \
	    tensorflow_text==2.12.1 \
	    tensorflow-gan==2.1.0 
RUN   python3 -m pip install --no-cache-dir \
        tensorflow[and-cuda]==2.15.1 \
	    keras==2.15.0 \
	    Keras-Applications==1.0.8 \
	    Keras-Preprocessing==1.1.2 \
	    tensorboard-plugin-wit \
	    tensorboard numpy scipy
RUN python3 -m pip install --no-cache-dir \
	    transformers \
	    accelerate \
	    xformers \
	    gradio

# Install Horovod, temporarily using CUDA stubs
RUN CUDA_HOME=/usr/local/cuda-12.4 \
    HOROVOD_WITHOUT_GLOO=1 \
    HOROVOD_CUDA_HOME=/usr/local/cuda-12.4 \
    HOROVOD_NCCL_LINK=SHARED \
    HOROVOD_GPU_OPERATIONS=NCCL \
    HOROVOD_WITH_MPI=1 \
    HOROVOD_WITHOUT_PYTORCH=1 \
    HOROVOD_WITH_TENSORFLOW=1 \
    HOROVOD_WITHOUT_MXNET=1 \
    pip install --no-cache-dir git+https://github.com/thomas-bouvier/horovod.git@compile-cpp17


RUN python3 -m pip install --no-cache-dir \
            mpi4py==3.1.4 \
            nni==2.10 \
            mlflow==2.0.1 \
            scikit-nni==0.2.1 \ 
			importlib-metadata==4.8.3 \
			blinker==1.4 \
			pytz==2022.7 \
			packaging==21.3

# Install ipython kernelspec
RUN python3 -m pip install ipykernel && \
    python3 -m ipykernel install --display-name "TensorFlow 2.15.1 on Python 3.10 & CUDA 12.4" && \
    cat /usr/local/share/jupyter/kernels/python3/kernel.json

# Copy Backend.Ai multi-node support
COPY ./service-defs /etc/backend.ai/service-defs
COPY ./runner-scripts/bootstrap.sh runner-scripts/setup_multinode.py /opt/container/

# Backend.AI specifics
LABEL ai.backend.kernelspec="1" \
      ai.backend.envs.corecount="OPENBLAS_NUM_THREADS,OMP_NUM_THREADS,NPROC" \
      ai.backend.features="batch query uid-match user-input" \
      ai.backend.base-distro="ubuntu22.04" \
      ai.backend.resource.min.cpu="1" \
      ai.backend.resource.min.mem="1g" \
      ai.backend.resource.min.cuda.device=0 \
      ai.backend.resource.min.cuda.shares=0 \
      ai.backend.runtime-type="python" \
      ai.backend.runtime-path="/usr/bin/python3" \
      ai.backend.service-ports="ipython:pty:3000,jupyter:http:8081,jupyterlab:http:8090,vscode:http:8180,tensorboard:http:6006,mlflow-ui:preopen:5000,nniboard:preopen:8080"
      
WORKDIR /home/work
