FROM lablup/common-base:20.09-cuda10.1

# Install TensorFlow, Keras, PyTorch and MXNet
ENV TENSORFLOW_VERSION=2.1.2

RUN python3 -m pip install --no-cache-dir --upgrade \
	    -q git+https://github.com/google-research/tensorflow_constrained_optimization 

RUN python3 -m pip install --no-cache-dir -I \
	    tensorflow-transform==0.21.2 \
	    tensorflow_model_analysis==0.21.6 \
	    tensorflow-metadata==0.21.1 \
	    tensorflow-datasets==2.1.0 \
	    tensorflow_probability \ 
	    tensorflow-addons==0.8.3 \
	    neural-structured-learning \
	    tensorflow-model-optimization \
	    tfx==0.22.0 \
	    tfx-bsl==0.22.0 \
	    tf-agents==0.5.0  \
	    tensorflow_constrained_optimization \
	    tensorflow-hub==0.8.0 \
	    tensorflow_text==2.1.1 \
	    tensorflow-graphics-gpu==1.0.0 \
	    tensorflow-gan==2.0.0 \
	    tensorflow-data-validation==0.22.2 \
	    tensorflow-plot==0.3.2 \
	    tensorflow-lattice==2.0.5 \
	    tensorflow_ranking==0.3.1 \
	    tensorflow-compression==1.3 \
	    mesh-tensorflow==0.1.13 \
	    tensorflow-io==0.12.0  \
	    jupyterlab-nvdashboard==0.3.1 \
    	    tensorflow==${TENSORFLOW_VERSION}  \
       	    tensorboard==2.1.1 
RUN python3 -m pip uninstall -y \
	    numpy==1.19.2 \
	    scipy==1.4.1 \
            tensorflow==2.3.1 \
	    tensorflow-gpu==2.3.1 \
	    && \
    rm -rf /var/lib/apt/lists/* && \	
    rm -rf /root/.cache 

WORKDIR /tmp
COPY ./numpy-1.18.5-cp36-cp36m-linux_x86_64.whl /tmp

# Install scipy
RUN git clone --branch=v${SCIPY_VERSION} --depth=1 https://github.com/scipy/scipy.git scipy && \
    cd scipy && \
    git checkout -b v${SCIPY_VERSION} && \  
    cp site.cfg.example site.cfg && \
    echo "[mkl]" >> site.cfg && \
    echo "include_dirs = /opt/intel/compilers_and_libraries_2020.3.279/linux/mkl/include/" >> site.cfg && \
    echo "library_dirs = /opt/intel/compilers_and_libraries_2020.3.279/linux/mkl/lib/intel64" >> site.cfg && \
    echo "mkl_libs = mkl_rt" >> site.cfg && \
    echo "lapack_libs =" >> site.cfg && \
    python3 -m pip install -U --no-cache-dir \
        cython \
	/tmp/numpy-1.18.5-cp36-cp36m-linux_x86_64.whl && \
    python3 setup.py install 

RUN python3 -m pip install --no-cache-dir \	    
       	    tensorboard==2.1.1 \
	    && \
    python3 -m pip uninstall -y \
	    tensorflow==2.1.1 && \
    python3 -m pip install --no-cache-dir \	    
    	    tensorflow-gpu==${TENSORFLOW_VERSION}  

RUN python3 -m pip install --extra-index-url \
       https://developer.download.nvidia.com/compute/redist nvidia-dali-cuda100 \
       && \
    python3 -m pip install --extra-index-url \
       https://developer.download.nvidia.com/compute/redist nvidia-dali-tf-plugin-cuda100
	    
# Install Horovod, temporarily using CUDA stubs
RUN ldconfig /usr/local/cuda/targets/x86_64-linux/lib/stubs && \
    HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_GPU_BROADCAST=NCCL \
    HOROVOD_WITH_TENSORFLOW=1 HOROVOD_WITHOUT_PYTORCH=1 HOROVOD_WITHOUT_MXNET=1 \
    pip install --no-cache-dir horovod==0.19.5 && \
    ldconfig

RUN python3 -m pip install --no-cache-dir \
    	    mpi4py==3.0.3 \
	    nni==1.8 \
	    scikit-nni==0.2.1

# Install ipython kernelspec
Run python3 -m ipykernel install --display-name "TensorFlow 2.1 on Python 3.6 (CUDA 10.1)" && \
    cat /usr/local/share/jupyter/kernels/python3/kernel.json

# Backend.AI specifics
LABEL ai.backend.kernelspec="1" \
      ai.backend.envs.corecount="OPENBLAS_NUM_THREADS,OMP_NUM_THREADS,NPROC" \
      ai.backend.features="batch query uid-match user-input" \
      ai.backend.base-distro="ubuntu16.04" \
      ai.backend.resource.min.cpu="1" \
      ai.backend.resource.min.mem="1g" \
      ai.backend.resource.min.cuda.device=0 \
      ai.backend.resource.min.cuda.shares=0 \
      ai.backend.runtime-type="python" \
      ai.backend.runtime-path="/usr/bin/python3" \
      ai.backend.service-ports="ipython:pty:3000,jupyter:http:8080,jupyterlab:http:8090,vscode:http:8180,tensorboard:http:6006"

WORKDIR /home/work
# vim: ft=dockerfile
