FROM lablup/common-base:20.07-py36-cuda10.1

# Install TensorFlow, Keras, PyTorch and MXNet
ENV TENSORFLOW_VERSION=2.1.1

ENV PYTHONUNBUFFERED=1 \
    LD_LIBRARY_PATH="/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/local/nvidia/lib64:/usr/include/x86_64-linux-gnu" \
    PATH="/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin/mecab" \
    LANG=C.UTF-8

# Set default shell to /bin/bash
SHELL ["/bin/bash", "-cu"]

RUN python3 -m pip install --no-cache-dir --upgrade \
	    gast==0.2.2 \
	    'httplib2<0.18.0,>=0.8' \
	    'coverage<5.0,>=4.5' \
	    'mock<4.0,>=3.0' \
    	    tensorflow==${TENSORFLOW_VERSION}  \
       	    tensorboard==2.1.1 

RUN python3 -m pip install --no-cache-dir --upgrade \
	    -q git+https://github.com/google-research/tensorflow_constrained_optimization 
RUN python3 -m pip install --no-cache-dir --upgrade \
	    -q git+https://github.com/tensorflow/fairness-indicators
RUN python3 -m pip install --no-cache-dir \
	    cachetools==3.1.0 \
	    tensorflow-transform==0.21.2 \
	    tensorflow_model_analysis==0.21.6 \
	    ngraph-tensorflow-bridge==0.18.0 \
	    tensorflow-metadata==0.21.1 \
	    tensorflow-datasets==2.1.0 \
	    tensorflow_probability \ 
	    tensorflow-addons==0.8.3 \
	    neural-structured-learning \
	    tensorflow-model-optimization \
	    tfx==0.22.0 \
	    tfx-bsl==0.22.0 \
	    tf-agents==0.5.0  \
	    tensorflow_constrained_optimization \
	    tensorflow-hub==0.8.0 \
	    tensorflow_text==2.2.1 \
	    tensorflow-graphics-gpu==1.0.0 \
	    tensorflow-gan==2.0.0 \
	    tensorflow-data-validation==0.22.0 \
	    jupyter-tensorboard==0.2.0 \
	    tensorflow-plot==0.3.2 \
	    tensorflow-lattice==2.0.5 \
	    tensorflow_ranking==0.3.1 \
	    tensorflow-compression==1.3 \
	    tensor2tensor \
	    mesh-tensorflow==0.1.13 \
    	    tensorwatch==0.9.1 \
	    tensorflow-io==0.13.0  \
	    jupyterlab-nvdashboard==0.3.1 \
    	    tensorflow==${TENSORFLOW_VERSION}  \
       	    tensorboard==2.1.1 

RUN python3 -m pip install --no-cache-dir --extra-index-url \
    	    https://developer.download.nvidia.com/compute/redist \
	    nvidia-dali-cuda100 && \
    python3 -m pip install --no-cache-dir --extra-index-url \
	    https://developer.download.nvidia.com/compute/redist nvidia-dali-tf-plugin-cuda100
	    
# Install Horovod, temporarily using CUDA stubs
RUN ldconfig /usr/local/cuda/targets/x86_64-linux/lib/stubs && \
    HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_GPU_BROADCAST=NCCL \
    HOROVOD_WITH_TENSORFLOW=1 HOROVOD_WITHOUT_PYTORCH=1 HOROVOD_WITHOUT_MXNET=1 \
    pip install --no-cache-dir horovod==0.19.4 && \
    ldconfig

RUN python3 -m pip install --no-cache-dir \
    	    mpi4py==3.0.3 \
	    nni==1.6 \
	    scikit-nni==0.2.1

# Install ipython kernelspec
Run python3 -m ipykernel install --display-name "TensorFlow 2.1 on Python 3.6 (CUDA 10.1)" && \
    cat /usr/local/share/jupyter/kernels/python3/kernel.json

RUN jupyter nbextension enable --py --sys-prefix widgetsnbextension && \
    jupyter nbextension enable --py tensorflow_model_analysis

# Backend.AI specifics
LABEL ai.backend.kernelspec="1" \
      ai.backend.envs.corecount="OPENBLAS_NUM_THREADS,OMP_NUM_THREADS,NPROC" \
      ai.backend.features="batch query uid-match user-input" \
      ai.backend.base-distro="ubuntu16.04" \
      ai.backend.resource.min.cpu="1" \
      ai.backend.resource.min.mem="1g" \
      ai.backend.resource.min.cuda.device=0 \
      ai.backend.resource.min.cuda.shares=0 \
      ai.backend.runtime-type="python" \
      ai.backend.runtime-path="/usr/bin/python3" \
      ai.backend.service-ports="ipython:pty:3000,jupyter:http:8080,jupyterlab:http:8090,vscode:http:8180,tensorboard:http:6006"

WORKDIR /home/work
# vim: ft=dockerfile
