FROM tensorflow/tensorflow:2.20.0-gpu

ARG CODE_SERVER_VERSION=4.107.0 \
    GIT_LFS_VERSION=3.7.1

ENV DEBIAN_FRONTEND=noninteractive \
    MPLBACKEND=Svg \
    PIP_IGNORE_INSTALLED=0 \
    PIP_BREAK_SYSTEM_PACKAGES=1 \
    PYTHONUNBUFFERED=1 \
    LANG=C.UTF-8

RUN apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com
RUN apt-get update
RUN apt-get install -y --no-install-recommends \
	automake \
	bison \
	build-essential \
	bzip2 \
	ca-certificates \
	cabextract \
	cmake \
	chrpath \
	devscripts \
	dh-make \
	dirmngr \
	dkms \
	ethtool \
	fakeroot \
	ffmpeg \
	flex \
	fonts-nanum \
	fonts-nanum-coding \
	fonts-nanum-extra \
	g++ \
	gcc \
	gdal-bin \
	gfortran \
	gir1.2-gtk-3.0 \
	git \
	gnupg \
	graphviz \
	htop \
	iputils-ping \
	libasound2-dev \
	libatlas-base-dev \
	libavcodec-dev \
	libavformat-dev \
	libboost-dev \
	libboost-filesystem-dev \
	libboost-system-dev \
	libcairo2-dev \
	libcurl4-openssl-dev \
	libdc1394-dev \
	libeigen3-dev \
	libfaac-dev \
	libfftw3-dev \
	libflatbuffers-dev \
	libfreetype-dev \
	libfuse2 \
	libgdal-dev \
	libgeos++-dev \
	libgeos-dev \
	libgflags-dev \
	libgirepository1.0-dev \
	libglib2.0-0 \
	libgoogle-glog-dev \
	libgphoto2-dev \
	libgstreamer-plugins-base1.0-dev \
	libgstreamer1.0-dev \
	libgtk-3-dev \
	libhdf5-dev \
	libjemalloc-dev \
	libjpeg-dev \
	liblapack-dev \
	libmnl0 \
	libmp3lame-dev \
	libncurses-dev \
	libnl-3-200 \
	libnl-3-dev \
	libnl-route-3-200 \
	libnl-route-3-dev \
	libnlopt-dev \
	libnuma-dev \
	libopenblas-dev \
	libopencore-amrnb-dev \
	libopencore-amrwb-dev \
	libopenmpi-dev \
	libpci3 \
	libpng-dev \
	libportmidi-dev \
	libproj-dev \
	libprotobuf-dev \
	libsdl2-dev \
	libsdl-image1.2-dev \
	libsdl-mixer1.2-dev \
	libsdl-ttf2.0-dev \
	libsm6 \
	libsmpeg-dev \
	libssl-dev \
	libswscale-dev \
	libswresample-dev \
	libtbb-dev \
	libtheora-dev \
	libtiff-dev \
	libv4l-dev \
	libvorbis-dev \
	libx264-dev \
	libxext6 \
	libxine2-dev \
	libxml2-dev \
	libxrender-dev \
	libxrender1 \
	libxslt1-dev \
	libxvidcore-dev \
	libyaml-dev \
	libzmq3-dev \
	lintian \
	lsof \
	make \
	mercurial \
	media-types \
	mailcap \
	ncurses-term \
	net-tools \
	ninja-build  \
	openjdk-11-jdk \
	openmpi-bin \
	openssh-client \
	openssh-server \
	pbzip2 \
	pciutils \
	pdsh \
	pkg-config \
	proj-bin \
	protobuf-compiler \
	pv \
	python-is-python3 \
	python3-dev \
	python3-xkit \
	python3-gdal \
	screen-resolution-extra \
	sudo \
	subversion \
	swig \
	tk \
	unzip \
	v4l-utils \
	vim \
	x264 \
	xvfb \
	xz-utils \
	sudo \
	yasm \
	zip \
	tcl \
	udev

# NVIDIA CUDA repository keyring + repo 등록
RUN curl -fsSL https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb -o /tmp/cuda-keyring.deb \
    && dpkg -i /tmp/cuda-keyring.deb 

RUN apt-get update && apt-get install -y --no-install-recommends \
    'libnccl2=2.*+cuda12.3' \
    'libnccl-dev=2.*+cuda12.3' && \ 
    ln -s /usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.6 /usr/local/cuda/lib64/libcudnn.so && \
    ldconfig

# Install Node.js (LTS) + yarn
RUN cd /tmp && \
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get update && apt-get install -y nodejs && \
    npm install -g corepack && \
    corepack enable && \
    corepack prepare yarn@stable --activate


WORKDIR /tmp
RUN dpkgArch="$(dpkg --print-architecture)"; \
    case "${dpkgArch##*-}" in \
        amd64) openblasTarget='CORE2'; crossCompile='0'; EXTRA_FLAGS="DYNAMIC_ARCH=1"; ;; \
        arm64) openblasTarget='ARMV8'; crossCompile='1'; EXTRA_FLAGS=""; ;; \
        *) echo >&2 "Unsupported: $dpkgArch"; exit 1 ;; \
    esac; \
    git clone -q --branch=v0.3.30 https://github.com/OpenMathLib/OpenBLAS.git && \
    cd OpenBLAS && \
    make TARGET=${openblasTarget} CROSS=${crossCompile} ${EXTRA_FLAGS} NO_AFFINITY=1 NUM_THREADS=48 FC=gfortran && \
    make install

# install git-lfs
WORKDIR /tmp
RUN cd /tmp && \
    dpkgArch="$(dpkg --print-architecture)"; \
    case "${dpkgArch##*-}" in \
        amd64) tarArch='amd64'; dirArch='x64';; \
        arm64) tarArch='arm64'; dirArch='aarch64';; \
        *) echo >&2 "error: current architecture ($dpkgArch) does not have a corresponding binary release"; exit 1 ;; \
    esac; \
    \
    curl -sLO "https://github.com/git-lfs/git-lfs/releases/download/v${GIT_LFS_VERSION}/git-lfs-linux-${tarArch}-v${GIT_LFS_VERSION}.tar.gz" && \
    tar -zxf "git-lfs-linux-${tarArch}-v${GIT_LFS_VERSION}.tar.gz" && \
    cd /tmp/git-lfs-${GIT_LFS_VERSION} && \
    bash install.sh

RUN dpkgArch="$(dpkg --print-architecture)"; \
    case "${dpkgArch##*-}" in \
        amd64) tarArch='amd64'; dirArch='x64';; \
        arm64) tarArch='arm64'; dirArch='aarch64';; \
        *) echo >&2 "error: current architecture ($dpkgArch) does not have a corresponding binary release"; exit 1 ;; \
    esac; \
     curl -fL https://github.com/cdr/code-server/releases/download/v${CODE_SERVER_VERSION}/code-server-${CODE_SERVER_VERSION}-linux-${tarArch}.tar.gz \
      | tar -C /usr/local/lib -xz && \
    mv /usr/local/lib/code-server-${CODE_SERVER_VERSION}-linux-${tarArch} /usr/local/lib/code-server-${CODE_SERVER_VERSION} && \
    ln -s /usr/local/lib/code-server-${CODE_SERVER_VERSION}/bin/code-server /usr/local/bin/code-server

RUN python3 -m pip install --no-cache-dir --upgrade \
        -q git+https://github.com/google-research/tensorflow_constrained_optimization
        
RUN python3 -m pip install --no-cache-dir \
        requests_oauthlib==2.0.0 \
        neural-structured-learning==1.4.0 \
        pydot==4.0.1 \
        proto-plus==1.27.0

RUN python3 -m pip install --no-cache-dir \
        tensorflow-datasets==4.9.9 \
        tensorflow-datasets-ko==0.2.3 \
        tensorflow_probability==0.23.0 \ 
        tensorflow-addons==0.23.0 \
        tensorflow-model-optimization==0.8.0 \
        tf-agents==0.19.0  

RUN python3 -m pip install --no-cache-dir \
        google_cloud_spanner==3.61.0 \
        googleapis-common-protos==1.72.0 \
        google_cloud_videointelligence==2.17.0 \
        google_cloud_vision==3.11.0 \
        google_cloud_pubsub==2.34.0 \
        google_cloud_dlp==3.33.0 \
        google_cloud_datastore==2.23.0 \
        google_cloud_bigtable==2.35.0 \
        google-api-core[grpc,grpcgcp]==2.29.0 \
        google_api_core==2.29.0

RUN python3 -m pip install --no-cache-dir \
        mesh-tensorflow==0.1.21 \
        tensorflow-hub==0.16.1 \
        tensorflow-data-validation==1.16.1

RUN python3 -m pip install --no-cache-dir \
        tensorflow-io==0.37.1 \
        tensorflow-plot==0.3.2 \
        tensorflow-gan==2.1.0

RUN   python3 -m pip install --no-cache-dir \
        tensorflow[and-cuda]==2.20.0 \
        keras==3.11.2 \
        Keras-Applications==1.0.8 \
        Keras-Preprocessing==1.1.2 \
        tensorboard-plugin-wit \
        tensorboard numpy scipy

RUN python3 -m pip install --no-cache-dir \
        transformers \
        accelerate \
        xformers \
        gradio

# Install Horovod, temporarily using CUDA stubs
RUN set -eux; \
    git clone --depth 1 https://github.com/horovod/horovod.git /tmp/horovod; \
    \
    # old XLA include path -> new XLA include path
    sed -i 's|tensorflow/compiler/xla/client/xla_builder.h|xla/hlo/builder/xla_builder.h|g' \
      /tmp/horovod/horovod/tensorflow/xla_mpi_ops.cc; \
    \
	# xla_mpi_ops.cc가 CMakeLists에 들어간 곳을 찾아서 제거
    grep -R --line-number "xla_mpi_ops\.cc" /tmp/horovod/horovod | head -n 50 || true; \
    for f in $(grep -R -l "xla_mpi_ops\.cc" /tmp/horovod/horovod | grep CMakeLists.txt || true); do \
      echo "patching $f"; \
      sed -i -E '/xla_mpi_ops\.cc/d' "$f"; \
    done; \
	# LBFGS++ 헤더 가져와서 third_party include에 배치
    git clone --depth 1 https://github.com/yixuan/LBFGSpp.git /tmp/LBFGSpp; \
	mkdir -p /tmp/horovod/third_party/lbfgs/include/; \
    cp -a /tmp/LBFGSpp/include/* /tmp/horovod/third_party/lbfgs/include/; \
    CXXFLAGS="-Wno-error -Wno-error=deprecated-declarations -Wno-deprecated-declarations -Wno-error=strict-aliasing -fno-strict-aliasing" \
    CFLAGS="-Wno-error -Wno-error=deprecated-declarations -Wno-deprecated-declarations -Wno-error=strict-aliasing -fno-strict-aliasing" \
    CUDA_HOME=/usr/local/cuda-12.3 \
    HOROVOD_WITHOUT_GLOO=1 \
    HOROVOD_CUDA_HOME=/usr/local/cuda-12.3 \
    HOROVOD_NCCL_LINK=SHARED \
    HOROVOD_GPU_OPERATIONS=NCCL \
    HOROVOD_WITH_MPI=1 \
    HOROVOD_WITHOUT_PYTORCH=1 \
    HOROVOD_WITH_TENSORFLOW=1 \
    HOROVOD_WITHOUT_MXNET=1 \
    HOROVOD_CMAKE=/usr/bin/cmake \
    pip install --no-cache-dir /tmp/horovod

RUN python3 -m pip install --no-cache-dir \
            mpi4py==4.1.1 \
            nni==3.0 \
            mlflow==3.8.1 \
            scikit-nni==0.2.1 \ 
            importlib-metadata==4.13.0 \
            blinker==1.4 \
            pytz==2025.2 \
            packaging==25.0

# Install ipython kernelspec
RUN python3 -m pip install ipykernel && \
    python3 -m ipykernel install --display-name "TensorFlow 2.20.0 on Python 3.11 & CUDA 12.3" && \
    cat /usr/local/share/jupyter/kernels/python3/kernel.json

# Copy Backend.Ai multi-node support
COPY ./service-defs /etc/backend.ai/service-defs
COPY ./runner-scripts/bootstrap.sh runner-scripts/setup_multinode.py /opt/container/

# Backend.AI specifics
LABEL ai.backend.kernelspec="1" \
      ai.backend.envs.corecount="OPENBLAS_NUM_THREADS,OMP_NUM_THREADS,NPROC" \
      ai.backend.features="batch query uid-match user-input" \
      ai.backend.base-distro="ubuntu22.04" \
      ai.backend.resource.min.cpu="1" \
      ai.backend.resource.min.mem="1g" \
      ai.backend.resource.min.cuda.device=0 \
      ai.backend.resource.min.cuda.shares=0 \
      ai.backend.runtime-type="python" \
      ai.backend.runtime-path="/usr/bin/python3" \
      ai.backend.service-ports="ipython:pty:3000,jupyter:http:8081,jupyterlab:http:8090,vscode:http:8180,tensorboard:http:6006,mlflow-ui:preopen:5000,nniboard:preopen:8080"


# Install Jupyterlab extensions
RUN python3 -m pip install --no-cache-dir \
    jupyter_nbextensions_configurator>=0.6.5 \
	jupyter_core \
	jupyter-contrib-core>=0.4.2 \
	jupyter-highlight-selected-word>=0.2.0 \
	jupyter-server>=2.17.0 \
    jupyter_lsp>=2.3.0 \
	jupyter-dash \
	jupyter-js-widgets-nbextension \
	jupyter-latex-envs \
	jupyter-packaging \
	jupyterlab==4.4.10 \
	jupyterlab-code-formatter>=3.0.2 \
	jupyterlab-hdf \
	jupyterlab-launcher \
	jupyterlab-widgets==3.0.16 \
    notebook \
	jupyter-server-mathjax \
	jupyter-server-proxy>=4.4.0 \
	jupyter-telemetry==0.1.0 \
	jupyter>=1.1.1 \
	jupyter-client==8.6.3 \
	jupyter_bokeh==2.0.4 \
	markupsafe>=3.0.2 \
	jsonschema[format,format-nongpl]>=4.23.0

RUN python3 -m pip install jupyter_lsp markupsafe==3.0.2 jupyterlab_widgets && \
    jupyter labextension install --no-build @jupyter-widgets/jupyterlab-manager && \
	jupyter labextension install --no-build @jupyter-widgets/controls && \
    jupyter labextension install --no-build @jupyterlab/toc-extension && \
    jupyter labextension install --no-build @krassowski/jupyterlab-lsp && \
    jupyter labextension install @jupyterlab/toc-extension && \
    jupyter lab build --dev-build=False --minimize=False

RUN apt-get autoclean && \
    sed -i 's/source \/usr\/local\/nvm\/nvm.sh//' /etc/bash.bashrc && \
    ln -sf /usr/share/terminfo/x/xterm-color /usr/share/terminfo/x/xterm-256color && \
    rm -f /tmp/*.whl /tmp/requirem* && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /root/.cache && \
    rm -rf /tmp/*

# change permission
RUN chown root:root /usr/lib

WORKDIR /home/work
