FROM python:3.6-alpine3.8

ENV MAKEFLAGS -j
ENV MAKEOPTS -j
RUN apk update && apk add --no-cache build-base

WORKDIR /root

RUN pip install -U pip setuptools
RUN pip install --no-binary --no-cache-dir Cython
RUN apk add --no-cache libuv-dev zeromq-dev snappy-dev
RUN pip wheel --no-deps pyzmq
RUN pip wheel --no-deps msgpack
RUN pip wheel --no-deps uvloop
RUN pip wheel --no-deps python-snappy

# List up built wheel packages
RUN ls -lh /root

# vim: ft=dockerfile
