FROM ubuntu:18.04
# Ubuntu 18.04 comes with Python 3.6

RUN apt-get update && \
    apt-get install -y \
        ca-certificates \
        wget curl git-core \
        vim-tiny zip unzip \
        python3 python3-pip \
        libssl-dev \
        libmpdec2 \
        proj-bin libproj-dev \
        libgeos-dev libgeos++-dev \
        mime-support \
        gcc g++ \
        cmake ncurses-term && \
    ln -sf /usr/share/terminfo/x/xterm-color /usr/share/terminfo/x/xterm-256color && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/

RUN apt-get update && \
    apt-get install -y software-properties-common && \
        add-apt-repository ppa:deadsnakes/ppa && \
	apt-get update && \
	apt-get install -y python3.7 python3.7-dev && \
	apt-get install -y cmake && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/

ENV PYTHONUNBUFFERED=1 \
    PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    LANG=C.UTF-8

RUN curl https://bootstrap.pypa.io/get-pip.py | python3.7 && \
    python3.7 -m pip install --no-cache-dir -U setuptools && \
    python3.7 -m pip install --no-cache-dir h5py && \
    python3.7 -m pip install --no-cache-dir Cython && \
    python3.7 -m pip install --no-cache-dir matplotlib bokeh && \
    python3.7 -m pip install --no-cache-dir versioneer==0.17 && \
    python3.7 -m pip install --no-cache-dir pyproj Cartopy==0.16 && \
    python3.7 -m pip install --no-cache-dir pandas && \
    python3.7 -m pip install --no-cache-dir seaborn && \
    python3.7 -m pip install --no-cache-dir pillow && \
    python3.7 -m pip install --no-cache-dir networkx cvxpy && \
    python3.7 -m pip install --no-cache-dir scikit-learn scikit-image && \
    python3.7 -m pip install --no-cache-dir pygments && \
    python3.7 -m pip install --no-cache-dir ipython && \
    python3.7 -m pip install --no-cache-dir jupyter && \
    python3.7 -m pip install --no-cache-dir jupyterlab && \
    rm -rf /root/.cache && \
    rm -f /tmp/*.whl
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.7 2
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 2

# Install ipython kernelspec
RUN python3.7 -m ipykernel install --display-name "Python 3.7 on Backend.AI" && \
    cat /usr/local/share/jupyter/kernels/python3/kernel.json

# Backend.AI specifics
COPY ./service-defs /etc/backend.ai/service-defs
LABEL ai.backend.kernelspec="1" \
      ai.backend.envs.corecount="OPENBLAS_NUM_THREADS,OMP_NUM_THREADS,NPROC" \
      ai.backend.features="batch query uid-match user-input" \
      ai.backend.resource.min.cpu="1" \
      ai.backend.resource.min.mem="256m" \
      ai.backend.base-distro="ubuntu18.04" \
      ai.backend.runtime-type="python" \
      ai.backend.runtime-path="/usr/bin/python3" \
      ai.backend.service-ports="ipython:pty:3000,jupyter:http:8070,jupyterlab:http:8090"
COPY policy.yml /etc/backend.ai/jail/policy.yml

# vim: ft=dockerfile
