FROM continuumio/anaconda3:2018.12
# This image bases on Debian.
# jail/hook binaries from ubuntu 16.04 are still compatible.

# Prepare for jail/hook minimal dependencies
RUN apt-get update && \
    apt-get install -y libseccomp2 libstdc++5 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/

# Prepare runtime environment
ENV PYTHONUNBUFFERED=1 \
    PATH=/opt/conda/bin:/opt/backend.ai/bin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    LANG=C.UTF-8
WORKDIR /home/work
EXPOSE 2000 2001

LABEL ai.backend.envs.corecount="OPENBLAS_NUM_THREADS,OMP_NUM_THREADS,NPROC" \
      ai.backend.features="batch query uid-match user-input" \
      ai.backend.base-distro="ubuntu16.04" \
      ai.backend.service-ports="ipython:pty:3000,jupyter:http:8080"

COPY policy.yml /etc/backend.ai/jail/policy.yml
ENTRYPOINT []
CMD ["/opt/backend.ai/bin/entrypoint.sh", \
     "/opt/backend.ai/bin/jail", "-policy", "/etc/backend.ai/jail/policy.yml", \
     "/opt/backend.ai/bin/python", "-m", "ai.backend.kernel", "python", \
     "/opt/conda/bin/python"]

RUN apt-get update && \
    apt-get install -y \
        ca-certificates \
        wget curl git-core \
        libssl-dev \
        libmpdec2 \
        proj-bin libproj-dev \
        libgeos-dev libgeos++-dev \
        mime-support \
        gcc g++ && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/

RUN conda install matplotlib bokeh && \
    conda install pyproj Cartopy && \
    conda install seaborn && \
    conda install h5py && \
    conda install pillow

# vim: ft=dockerfile
