FROM continuumio/anaconda3:2018.12
# Anaconda 2018.12 comes with Python 3.7

RUN apt-get update && \
    apt-get install -y \
        ca-certificates \
        wget curl git-core \
        libssl-dev \
        libmpdec2 \
        proj-bin libproj-dev \
        libgeos-dev libgeos++-dev \
        mime-support \
        gcc g++ && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/

ENV PYTHONUNBUFFERED=1 \
    PATH=/opt/conda/bin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    LANG=C.UTF-8

RUN conda install matplotlib bokeh && \
    conda install pyproj Cartopy && \
    conda install seaborn && \
    conda install h5py && \
    conda install pillow

# Install ipython kernelspec
RUN python -m ipykernel install --name backendai-python3.6 \
        --display-name "Python 3.6 on Backend.AI" && \
    cat /usr/local/share/jupyter/kernels/backendai-python3.6/kernel.json

# Backend.AI specifics
LABEL ai.backend.envs.corecount="OPENBLAS_NUM_THREADS,OMP_NUM_THREADS,NPROC" \
      ai.backend.features="batch query uid-match user-input" \
      ai.backend.base-distro="ubuntu16.04" \
      ai.backend.runtime-type="python" \
      ai.backend.runtime-path="/opt/conda/bin/python" \
      ai.backend.service-ports="ipython:pty:3000,jupyter:http:8080"
COPY policy.yml /etc/backend.ai/jail/policy.yml

# vim: ft=dockerfile
