FROM ubuntu:20.04
# Ubuntu 20.04 comes with Python 3.8
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && \
    apt-get install -y \
        ca-certificates \
        wget curl git-core \
        vim-tiny zip unzip \
        python3 python3-pip \
        libssl-dev \
        libmpdec2 \
        proj-bin libproj-dev \
        libgeos-dev libgeos++-dev \
        mime-support \
        gcc g++ \
        cmake \
        ncurses-term && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/

RUN ln -sf /usr/share/terminfo/x/xterm-color /usr/share/terminfo/x/xterm-256color

ENV PYTHONUNBUFFERED=1 \
    PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    LANG=C.UTF-8

RUN curl https://bootstrap.pypa.io/get-pip.py | python3 && \
    python3 -m pip install --no-cache-dir -U setuptools && \
    python3 -m pip install --no-cache-dir h5py && \
    python3 -m pip install --no-cache-dir Cython && \
    python3 -m pip install --no-cache-dir matplotlib bokeh && \
    python3 -m pip install --no-cache-dir versioneer && \
    python3 -m pip install --no-cache-dir pyproj Cartopy && \
    python3 -m pip install --no-cache-dir pandas && \
    python3 -m pip install --no-cache-dir seaborn && \
    python3 -m pip install --no-cache-dir pillow && \
    python3 -m pip install --no-cache-dir networkx cvxpy && \
    python3 -m pip install --no-cache-dir scikit-learn scikit-image && \
    python3 -m pip install --no-cache-dir pygments && \
    python3 -m pip install --no-cache-dir ipython && \
    python3 -m pip install --no-cache-dir jupyter && \
    python3 -m pip install --no-cache-dir jupyterlab && \
    rm -rf /root/.cache && \
    rm -f /tmp/*.whl
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 2

# Install jupyter & Julia
ARG JULIA_VERSION
ENV JULIA_VERSION ${JULIA_VERSION:-1.5.3}
ENV JULIA_PATH "/usr/local/julia"
ENV PATH $JULIA_PATH:$JULIA_PATH/bin:$PATH
    
RUN dpkgArch="$(dpkg --print-architecture)"; \
    case "${dpkgArch##*-}" in \
        amd64) tarArch='x86_64'; dirArch='x64';; \
        armhf) tarArch='arm'; dirArch='arm';; \
        i386) tarArch='i686'; dirArch='x86';; \
        *) echo >&2 "error: current architecture ($dpkgArch) does not have a corresponding Julia binary release"; exit 1 ;; \
    esac; \
    \
    curl -fL -o julia.tar.gz     "https://julialang-s3.julialang.org/bin/linux/${dirArch}/${JULIA_VERSION%[.-]*}/julia-${JULIA_VERSION}-linux-${tarArch}.tar.gz"; \
    \
    mkdir "$JULIA_PATH"; \
    tar -xzf julia.tar.gz -C "$JULIA_PATH" --strip-components 1; \
    rm julia.tar.gz

#add IJulia package to make Julia kernel available in jupyter
ENV JULIA_PKG_LOC /opt/julia
ENV JULIA_LOAD_PATH :/opt/julia
ENV JULIA_DEPOT_PATH /opt/julia
RUN mkdir ${JULIA_PKG_LOC}
RUN julia -e 'ENV["JUPYTER"]="jupyter"' && \
    julia -e 'ENV["PYTHON"]="python3"' && \
    julia -e 'ENV["JULIA_DEPOT_PATH"]="/opt/julia"' && \
    julia -e 'using Pkg; Pkg.add("IJulia");'

RUN julia -e 'using Pkg; Pkg.add("Plots"); using Plots;'
RUN julia -e 'using Pkg; Pkg.add("DataFrames");' && \
    julia -e 'using Pkg; Pkg.add("RDatasets");' && \
    julia -e 'using Pkg; Pkg.add("PyPlot");' && \
    julia -e 'using Pkg; Pkg.add("CSV");' && \
    julia -e 'using Pkg; Pkg.add("Pandas"); using Pandas;'

SHELL ["/bin/bash", "-c"]
RUN julia -e 'using IJulia' && \
    chmod -R 755 /opt/julia/compiled
SHELL ["/bin/sh", "-c"]
# Install ipython kernelspec
COPY kernel.json /usr/local/share/jupyter/kernels/julia-1.5/kernel.json
COPY logo-32x32.png /usr/local/share/jupyter/kernels/julia-1.5/logo-32x32.png
COPY logo-64x64.png /usr/local/share/jupyter/kernels/julia-1.5/logo-64x64.png

# Backend.AI specifics
LABEL ai.backend.kernelspec="1" \
      ai.backend.envs.corecount="OPENBLAS_NUM_THREADS,OMP_NUM_THREADS,NPROC" \
      ai.backend.features="batch query uid-match user-input" \
      ai.backend.resource.min.cpu="1" \
      ai.backend.resource.min.mem="512m" \
      ai.backend.base-distro="ubuntu20.04" \
      ai.backend.runtime-type="python" \
      ai.backend.runtime-path="/usr/bin/python3" \
      ai.backend.service-ports="ipython:pty:3000,jupyter:http:8070,jupyterlab:http:8090"
COPY policy.yml /etc/backend.ai/jail/policy.yml
ENV JULIA_DEPOT_PATH /home/work/.julia:/opt/julia
ENV JULIA_PROJECT /home/work/.julia
# vim: ft=dockerfile

