FROM alpine:3.8

RUN apk add --no-cache g++ gcc musl-dev make
WORKDIR /root
RUN git clone https://github.com/lablup/backend.ai-hook && \
    cd backend.ai-hook && \
    make inner

# vim: ft=dockerfile
