FROM bitnami/minideb:jessie as hook-builder
RUN install_packages gcc libc6-dev make git-core ca-certificates
WORKDIR /root
RUN git clone https://github.com/lablup/sorna-hook && \
    cd sorna-hook && \
    make inner
