FROM tensorflow/serving:2.7.4
# Backend.AI specifics
LABEL ai.backend.kernelspec="1" \
      ai.backend.envs.corecount="OPENBLAS_NUM_THREADS,OMP_NUM_THREADS,NPROC" \
      ai.backend.features="batch uid-match" \
      ai.backend.base-distro="ubuntu20.04" \
      ai.backend.resource.min.cpu="1" \
      ai.backend.resource.min.mem="1g" \
      ai.backend.runtime-type="app" \
      ai.backend.service-ports="tf-model-server-grpc:preopen:8500,tf-model-server-restapi:preopen:8501"
ENV USER work
WORKDIR /home/work