MAINTAINER Mario Cho "m.cho@lablup.com"

FROM ubuntu:18.04

RUN apt-get update && \
    apt-get install -y \
        python3 python3-pip \
	gfortran \
        libssl-dev \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/

ENV PATH=/opt/backend.ai/bin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    LANG=C.UTF-8 \
    DEBIAN_FRONTEND=noninteractive

# Install commonly-used wheels
RUN curl https://bootstrap.pypa.io/get-pip.py | python3 && \
    python3 -m pip install --no-cache-dir -U setuptools && \
    python3 -m pip install --no-cache-dir pyzmq && \
    python3 -m pip install --no-cache-dir ipython && \
    python3 -m pip install --no-cache-dir jupyter && \
    python3 -m pip install --no-cache-dir jupyterlab

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 2

COPY ./service-defs /etc/backend.ai/service-defs

# Install ipython kernelspec
RUN python3 -m ipykernel install --display-name "gFrotran 8.3 on Backend.AI" && \
    cat /usr/local/share/jupyter/kernels/python3/kernel.json

# Backend.AI specifics
LABEL ai.backend.kernelspec="1" \
      ai.backend.envs.corecount="OPENBLAS_NUM_THREADS,OMP_NUM_THREADS,NPROC" \
      ai.backend.features="batch query uid-match user-input" \
      ai.backend.resource.min.cpu="1" \
      ai.backend.resource.min.mem="256m" \
      ai.backend.base-distro="ubuntu16.04" \
      ai.backend.runtime-type="python" \
      ai.backend.runtime-path="/usr/bin/python3" \
      ai.backend.service-ports="jupyter:http:8080,vscode:http:8180,jupyterlab:http:8090"

# vim: ft=dockerfile

